# Advanced Configuration Example for dsmeta
# Full configuration with all available options

# Application settings
app_name: "dataset-annotation-tool"
version: "1.2.0"
debug: false

# LLM Configuration
llm:
  provider: "siliconflow"
  model: "THUDM/GLM-4-9B-0414"
  base_url: "https://api.siliconflow.cn/v1"
  api_key: "${SILICONFLOW_API_KEY}"  # Environment variable recommended
  temperature: 0.1
  max_tokens: 4000
  timeout: 60

# File Processing Configuration
file_processing:
  max_file_size: "100MB"  # Larger files for comprehensive datasets
  sample_head_lines: 2000
  sample_tail_lines: 200
  sample_random_size: 1000
  encoding_fallback:
    - "utf-8"
    - "gbk"
    - "latin-1"
    - "cp1252"

# Search Configuration - Web search for additional info
search:
  enabled: true
  provider: "tavily"
  api_key: "${TAVILY_API_KEY}"
  max_results: 15
  timeout: 45

# Output Configuration
output:
  template_dir: "./templates"
  default_template: "default.md.j2"
  output_formats:
    - "markdown"
    - "json"
    - "yaml"  # Include YAML export
  backup_existing: true

# Logging Configuration
logging:
  level: "DEBUG"  # More verbose for troubleshooting
  format: "json"
  file_path: "./logs/dsmeta.log"  # Log to file

# Monitoring Configuration (for watch mode)
monitoring:
  directories:
    - "/path/to/datasets"
  patterns:
    - "**/qiaoyu-*"
    - "**/dataset-*"
  recursive: true
  polling_interval: 30
  max_concurrent_tasks: 8
  cooldown_seconds: 10
  retry_attempts: 5
  queue_size: 1000

# Quality Control - Strict validation
quality_control:
  min_confidence_score: 0.8  # Higher threshold
  require_human_review_threshold: 0.6
  required_fields:
    - "name"
    - "description"
    - "modality"
    - "domain"
    - "use_case"
  enum_validation: true

# Node Configuration
node_config:
  max_retries: 5  # More retries for stability
  timeout: 120    # Longer timeout for complex datasets
  cache_enabled: true

# Custom field mapping for document parsing
document_parsing:
  field_patterns:
    custom_description: ["## 描述", "## Description"]
    custom_source: ["## 来源", "## Source"]
    custom_tags: ["## 标签", "## Tags"]
  
# Advanced LLM prompt customization
llm_prompts:
  preliminary_analysis:
    system_prompt: "你是一个专业的网络安全数据集分析专家..."
    max_context_length: 8000
  
  synthesis:
    temperature_override: 0.05  # More deterministic for final output
    include_reasoning: true